[package]
name = "aoc_03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2.0.4"
input_parser = { path = "../../utils/input_parser" }
regex = "1.10.2"
